posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

#Namespacing URL names
app_name = 'posts'

urlpatterns = [
    url(r'^$', views.post_list, name= 'list'),
    url(r'^about$', views.about, name ='about'),
    url(r'^create/$', views.post_create, name= 'create'),
    url(r'^(?P<slug>[\w-]+)/$', views.post_detail, name= 'detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.post_update, name= 'update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.post_delete, name= 'delete'),
]

posts/models.py
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify

from markdown_deux import markdown
from comments.models import Comment
from .utils import get_read_time
# Create your models here.

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())

def upload_location(instance, filename):
    return "%s/%s" %(instance.id, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    image = models.ImageField(null=True, blank=True,
                    upload_to=upload_location,
                    width_field='width_field',
                    height_field='height_field')
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    read_time = models.IntegerField(default=0)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    def get_markdown(self):
        content = self.content
        return mark_safe(markdown(content))

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type

    class Meta:
        ordering = ["-timestamp", "-updated"]

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by('-id')
    slug_exists = qs.exists()
    if slug_exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var

pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from .models import Post
from django.utils import timezone

class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget, initial=timezone.now().date())
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'image',
            'draft',
            'publish',
        ]

posts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404,redirect
from django.utils import timezone

from urllib.parse import quote_plus

from .models import Post
from .forms import PostForm
from comments.forms import CommentForm
from comments.models import Comment


def about(request):
    return render(request,'about.html', {})

# List of Blog Posts
def post_list(request):
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()
    else:
        queryset_list = Post.objects.active()
    search_query = request.GET.get("q")

    if search_query:
        queryset_list = queryset_list.filter(
                Q(title__icontains=search_query)|
				Q(content__icontains=search_query)|
				Q(user__first_name__icontains=search_query) |
				Q(user__last_name__icontains=search_query)
                ).distinct()

    paginator = Paginator(queryset_list, 2) # Show 5 Blog Posts per page
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    context = {
        'title': "List posts",
        'object_list': queryset,
        'page_request_var': page_request_var,
    }
    return render(request, 'post_list.html', context)


# Create a Blog Post
@login_required
def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "Sucessfully Created")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        'form': form,
    }
    return render(request, 'post_form.html', context)


# Retrieve a Blog Post's details
def post_detail(request, slug):
    instance = get_object_or_404(Post, slug = slug)
    if not request.user.is_staff or not request.user.is_superuser:
        if instance.draft or instance.publish > timezone.now().date():
            raise Http404

    share_string = quote_plus(instance.content)
    comments = instance.comments
    initial_data = {
        'content_type': instance.get_content_type,
        'object_id': instance.id,
    }

    form = CommentForm(request.POST or None, initial=initial_data)

    if form.is_valid() and request.user.is_authenticated():
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model= c_type)
        obj_id = form.cleaned_data.get("object_id")
        content_data = form.cleaned_data.get("content")
        parent_obj = None
        try:
            parent_id = request.POST.get("parent_id")
        except:
            parent_id = None

        if parent_id:
            parent_qs= Comment.objects.filter(id=parent_id)
            if parent_qs.exists():
                parent_obj = parent_qs.first()

        content = form.cleaned_data.get("content")
        new_comment, created = Comment.objects.get_or_create(
                            user= request.user,
                            content_type= content_type,
                            object_id = obj_id,
                            content= content,
                            parent= parent_obj,
                        )
        messages.success(request, "Sucessfully created comment")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        'title': instance.title,
        'instance': instance,
        'share_string': share_string,
        'comments': comments,
        'comment_form' : form
    }
    return render(request, 'post_detail.html' , context)


# Update an already created Blog Post
def post_update(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug = slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Sucessfully Saved")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        'title': "Detail",
        'instance': instance,
        'form': form,
    }
    return render(request, "post_form.html", context)


#TODO Search View


# Delete a Blog Post
@login_required
def post_delete(request, slug= None):
    """ Check if post exists """
    try:
        post_obj = Post.objects.get(slug=slug)
    except:
        raise Http404
    #
    if post_obj.user != request.user:
        messages.warning(request, "You cannot delete posts that are not yours.")
        error_context = {'error_message': "You do not have permission to view this.", 'code':403, }
        return render(request, "error.html", error_context, status=403) #Access Denied/Forbidden

    if request.method=='POST': #If user confirms delete
        post_obj.delete()
        messages.success(request, "Sucessfully deleted post")
        return redirect('posts:list')
    return render(request, "posts/confirm_delete.html", {"instance":post_obj, } )

templates/about.html
{% extends "base.html" %}
{% block title %} Home {% endblock title %}
{% block content %}

<div class="col-sm-6 col-sm-offset-3">
  <!-- Title -->
  <div class='page-title'>
    <h1>About Me</h1>
  </div>

  <div class='about-me'>
    <div class='col-md-6'>
      <img class='profile-pic' src='https://avatars1.githubusercontent.com/u/14945184?v=3&u=12e17b9c018e1fd87e666acc2bde84c623456534&s=400' />
    </div>
    <p class='lead'>
      My name is Andres Gajardo.  I am currently attending CUNY Queens College and pursuing a degree in computer science.
      My dream is to become a software engineer or full stack developer.  
    </p>
  </div>

  {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>

<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Andres Gajardo">

  <title> {% block title %}  {% endblock title %} | Andres' Blog </title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    crossorigin="anonymous" />

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
    integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
    crossorigin="anonymous"/>

  <!-- Custom font -->
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

  <!-- Custom Stylesheet -->
  <link rel='stylesheet' href='{% static "css/site_style.css" %}' />

  <style>
    {% block style %}     {% endblock style %}
  </style>

  {% block head_extra %}   {% endblock head_extra %}

  <!-- FontAwesome CDN -->
  <script src="https://use.fontawesome.com/f19450d790.js"></script>

</head>

<body>

<!-- Nav Bar-->

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Hamburger Menu for mobile/smaller display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            <a class="navbar-brand" href="{% url 'posts:list' %}"><i class="fa fa-futbol-o fa-1x" aria-hidden="true"></i> Andres' Blog</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'posts:about'%}">About Me</a>
                </li>
                <li>
                    <a href="#">Contact Me</a>
                </li>
                {% if request.user.is_staff or request.user.is_superuser %}
                <li>
                  <a href="{% url 'posts:create' %}">Create Post</a>
                </li>
                {% endif %}

                <!-- TODO: Float: right or pull-right-->
                {% if not request.user.is_authenticated %}
                  <li class=''>
                    <a class='login-btn'href="{% url 'login' %}"><i class="fa fa-sign-in fa-1x" aria-hidden="true"></i>
                      Login </a>
                  </li>
                  <li class=''>
                    <a class='register-btn' href="{% url 'register' %}"><i class="fa fa-user-plus fa-1x" aria-hidden="true"></i>
                      Register </a>
                  </li>
                {% else %}
                  <li class='logout-btn'>
                    <a class='pull-right' href="{% url 'logout' %}"><i class="fa fa-power-off fa-1x" aria-hidden="true"> </i>
                      Logout </a>
                  </li>
                {% endif %}
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

  <!-- Messages Bar -->
  {% if messages %}
    <div class='messages col-sm-6 col-sm-offset-3 text-center'>
      <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
    </div>
  {% endif %}

  <div class='container'>
    {% block content %}

    {% endblock content%}
  </div>


  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
  integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
  crossorigin="anonymous">
  </script>

  <!-- marked CDN: markdown parser and compiler -->
  <script src= "https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js"></script>

  <script type="text/javascript">
  $(document).ready(function(){

      $(".post-detail-item img").each(function(){
          $(this).addClass("img-responsive");
      });

      //Hide markdown images in post_list view
      $(".post-detail-caption img").each(function(){
          $(this).addClass("hidden");
      });

      // Show replies when clicked
      $(".comment-reply-btn").click(function(event){
        event.preventDefault();
        $(this).parent().parent().next(".comment-reply").fadeToggle();
      });

      //Preview Post Title and Content
      function setContent(value){
          var markedContent = marked(value);
          $("#preview-content").html(markedContent);
          $("#preview-content img").each(function(){
              $(this).addClass("img-responsive");
          });
      }
      var contentInput = $("#id_content");
      setContent(contentInput.val());

      contentInput.keyup(function(){
          var newContent = $(this).val();
          setContent(newContent);
      });

      //Title preview
      function setTitle(value) {
          $("#preview-title").text(value);
      }
      var titleInput = $("#id_title");

      setTitle(titleInput.val());

      titleInput.keyup(function(){
          var newContent = $(this).val();
          setTitle(newContent);
      });

    });
  </script>

</body>

</html>

templates/error.html
{% extends "base.html" %}

{% block content %}

<div class='header col-md-6'>
  <h1> {{ code }} error</h1>
  <h3> {{ error_message }} </h3>
</div>

{% endblock content %}

templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} {{title}}  {% endblock title %}

{% block content %}
<div class='col-sm-6' 'col-sm-offset-3'>
    <h1>{{ title }}</h1>
    <hr />

    <form method="POST" action='' enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form | crispy }}
        <input type='submit' class='btn btn-default' value='{{ title }}' />
    </form>
</div>
{% endblock content %}

templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block content %}

<div class='col-sm-6 col-sm-offset-3 post-entire'>
  <!-- Post details -->
    <div>
        <h1 class='post-title'> {{ instance.title }} {% if instance.draft%} <span class='draft'> Draft </span> {%endif%}</h1>
    </div>
    <h3 class='post-author'>
      {% if instance.user.get_full_name%}Author: {{ instance.user.get_full_name }}
      {% else %} User: {{ instance.user.username }}
      {% endif %}
    </h3>
    <p class='post-time'><small><i class="fa fa-clock-o fa-1x "></i>
      {{ instance.timestamp | date:"M j" }} - {{instance.read_time }} min read</small>
    </p>

    {% if instance.image %}
      <img src='{{ instance.image.url }}' class='img img-responsive post-image' />
    {% endif %}
    <hr />

    <div class="post-detail-item">{{ instance.get_markdown }}</div>

    <br/>
    <hr/>
    {% if request.user.is_staff or request.user.is_superuser or request.user == instance.user %}
      <div class='row'>
        <a class='btn btn-default' href="{% url 'posts:update' instance.slug %}"> Edit </a>
        <a class='btn btn-danger' href="{% url 'posts:delete' instance.slug %}"> Delete </a>
      </div>
    {% endif %}
    <p> <small>Updated: {{ instance.updated }}</small> </p>

    <!-- Social Media Share Buttons -->
    <div class='social-share'>
        <a class="fa fa-facebook-official fa-2x" href="https://www.facebook.com">
        </a>
        <a class="fa fa-twitter-square fa-2x" href="https://twitter.com/home?status={{ instance.content|truncatechars:40|urlify }}%20{{ request.build_absolute_uri }}">
        </a>
        <a class="fa fa-google-plus-square fa-2x" href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>
        </a>
    </div>

    <br/>

    <!-- Comments Secetion -->
    <div>
      <p class='lead'> Comments </p>
      {% if request.user.is_authenticated %}
        <form method="POST" action="."> {% csrf_token %}
          {{ comment_form | crispy }}
          <input type='submit' value='Post Comment' class='btn btn-default' />
        </form>
      {% else %}
        <p> You must be logged in to comment. </p>
      {% endif %}
      <hr />

      <!-- Top Level Comments -->
      {% for comment in comments %}
        <blockquote>
          <div class="row">
            <p> {{comment.content}} </p>
            <footer>via {{ comment.user }} {{comment.timestamp| timesince}} ago |
              {% if comment.children.count == 1 %} {{ comment.children.count }} Reply |
                {% endif %}
              {% if comment.children.count > 1 or comment.children.count == 0 %} {{ comment.children.count }} Replies |
                {% endif %}
              <a class='comment-reply-btn' href='#'> Reply</a>
              <a class='view-thread-btn' href="{{comment.get_absolute_url}}"> View Thread </a>
            </footer>
          </div>

          <!-- Replies -->
          <div class='comment-reply'>
            {% for child_comment in comment.children %}
              <blockquote>
                <p> {{child_comment.content}} </p>
                <footer> {{child_comment.timestamp| timesince}} ago | via {{ child_comment.user }} </footer>
              </blockquote>
            {% endfor %}

            {% if request.user.is_authenticated %}
              <form class='reply-form' method="POST" action="."> {% csrf_token %}
                {{ comment_form | crispy }}
                <input type='hidden' name='parent_id' value='{{ comment.id }}' />
                <input type='submit' value='Reply' class='btn btn-default' />
              </form>
              {% else %}
                <p><small> You must be logged in to comment. </small></p>
              {% endif %}
          </div>

        </blockquote>
        <hr/>
      {% endfor %}

    </div>

</div><!-- Close Post div-->

{% endblock content %}

templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-xs-4 post-form">
      <h1> Create a Post </h1>
      <hr />
      <form role ='form' method='POST' action='.' enctype='multipart/form-data'> {% csrf_token %}
      {{ form | crispy }}
      <!-- Submit Form button -->
      <div class='col-sm-4 btn btn-submit'>
          <input type='submit' value='Create Post' />
      </div>
    </form>
    {{form.media}}
    </div>

    <div class='col-xs-6 post-preview'>
    <h1>Post Preview</h1>
    <hr />
      <div class='content-preview'>
        <h3 id='preview-title'></h3>
        <p id='preview-content'></p>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/post_list.html
{% extends "base.html" %}
{% block title %} Home {% endblock title %}
{% block content %}

<div class="col-sm-6 col-sm-offset-3 post-list">
  <!-- Title -->
  <div class='page-title'>
    <h2> Recent Posts </h2>
  </div>

  <!-- Search -->
    <form class='row search-bar' method='GET' action=''>
      <div class="col-sm-6">
        <div class="input-group" >
          <input class='form-control' type='text' name='q' placeholder="Search posts" value='{{ request.GET.q}} '/>
          <span class='input-group-btn'>
            <button class='btn btn-default' type='submit'> Search <i class='fa fa-search'></i> </button>
          </span>
        </div>
      </div>
    </form>


  <!-- List each Blog Post -->
  {% for obj in object_list %}
    <div class="row post-box">
      <div class="col-sm-12">
        <div class="thumbnail">
          <!-- Post image-->
          {% if obj.image %}
            <img src='{{ obj.image.url }}' class='img img-responsive list-image' />
          {% endif %}
          <!-- Post preview -->
          <div class="caption">
            <h3>  <a class= 'post-title' href="{{ obj.get_absolute_url }}"> {{ obj.title }} </a>
              <small>
              {% if obj.draft %}
                <span style='color:rgb(215, 25, 25);'> (Draft) </span>
              {% endif %}
              </small>
              {% if obj.publish > today %}<h3> Future Post</h3> {% endif %}
            </h3>
            <small><i class="fa fa-clock-o fa-1x "></i> {{ obj.timestamp | timesince }} ago</small>

            <p> Author: {% if instance.user.get_full_name%}{{ instance.user.get_full_name }}
                        {% else %} {{ instance.user.username }}
                        {% endif %}
              </p>

            <div class='post-detail-caption'>
              <p>{{ obj.get_markdown | truncatechars_html:140 }} </p>
            </div>
            <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
          </div>

        </div>
        <hr/>
      </div>
      <hr/>
    </div>
    {# {% cycle "" "<div class='col-sm-12'><hr/></div></div><div class='row'>"%}#}

  {% endfor %}

  <!-- Paginator -->
  <div class="pagination col-sm-12">
    <nav aria-label="...">
      <ul class="pager">

        {% if object_list.has_previous %}
          <li>  <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Previous</a></li>
        {% endif %}

        <li>
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}
        </li>

        {% if object_list.has_next %}
          <li>  <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Next</a></li>
        {% endif %}

      </ul>
    </nav>
  </div>

</div> <!--Close post-list div -->

{% endblock content %}

templates/success.html
{% extends "base.html" %}

{% block title %} {{ title }} {% endblock title %}

{% block content %}
<div class='header col-md-6'>
  <h1>{{ title }}</h1>
  <h3>{{ success_message }}</h3>
</div>

{% endblock content %}