comments/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

#Namespacing URL names
app_name = 'comments'

urlpatterns = [
    url(r'^(?P<id>\d+)/$', views.comment_thread, name='thread'),
    url(r'^(?P<id>[\w-]+)/delete/$', views.comment_delete, name= 'delete'),

    #TODO
    #url(r'^(?P<slug>[\w-]+)/edit/$', views.comment_update, name= 'update'),
]

posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

#Namespacing URL names
app_name = 'posts'

urlpatterns = [
    url(r'^$', views.post_list, name= 'list'),
    url(r'^about$', views.about, name ='about'),
    url(r'^create/$', views.post_create, name= 'create'),
    url(r'^(?P<slug>[\w-]+)/$', views.post_detail, name= 'detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.post_update, name= 'update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.post_delete, name= 'delete'),
]

comments/models.py
from django.db import models
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse


# Model Manager
class CommentManager(models.Manager):
    def all(self):
        qs = super(CommentManager, self).filter(parent=None)
        return qs

    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance.id
        qs = super(CommentManager, self).filter(content_type= content_type, object_id= obj_id).filter(parent=None)
        return qs


class Comment(models.Model):
    user        = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    parent = models.ForeignKey("self", null= True, blank= True)

    content     = models.TextField()
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = CommentManager()

    class Meta:
        ordering = ['-timestamp']

    def get_absolute_url(self):
        return reverse("comments:thread", kwargs={"id":self.id})

    def children(self): #Replies
        return Comment.objects.filter(parent= self)

    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        return True


    def __str__(self):
        return str(self.user.username)

comments/forms.py
from django import forms

class CommentForm(forms.Form):
    content_type = forms.CharField(widget=forms.HiddenInput)
    object_id = forms.IntegerField(widget=forms.HiddenInput)
    #parent_id = forms.IntegerField(widget=forms.HiddenInput, required=False)       #replies
    content = forms.CharField(label='', widget=forms.Textarea)

comments/views.py
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404, HttpResponse


from .models import Comment
from .forms import CommentForm
# Create your views here.

@login_required
def comment_delete(request, id):
    try:
        obj = Comment.objects.get(id= id)
    except:
        raise Http404

    if obj.user != request.user:
        messages.warning(request, "You cannot delete comments that are not yours.")
        error_context = {'status_code' : 403, 'error_message': "You do not have permission to view this."}
        return render(request, "error.html", error_context, status=403) #Access Denied/Forbidden

    if request.method == "POST": #If user wishes to delete comment
        parent_obj_url = obj.content_object.get_absolute_url() # URL of post related to comment
        obj.delete() #Delete comment
        messages.success(request, "Comment has been deleted.")
        return HttpResponseRedirect(parent_obj_url)

    context = {
        "object": obj,
    }
    return render(request, "comments/confirm_delete.html", context)


def comment_thread(request, id):
    try:
        obj = Comment.objects.get(id= id)
    except:
        raise Http404

    if not obj.is_parent:
        obj = obj.parent

    initial_data = {
        "content_type": obj.content_type, #Post related to Comment Thread
        "object_id": obj.object_id,
    }

    form = CommentForm(request.POST or None, initial = initial_data)
    if form.is_valid() and request.user.is_authenticated():
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model= c_type)
        obj_id = form.cleaned_data.get("object_id")
        content_data = form.cleaned_data.get("content")
        parent_obj = None
        try:
            parent_id = request.POST.get("parent_id")
        except:
            parent_id = None

        if parent_id:
            parent_qs= Comment.objects.filter(id=parent_id)
            if parent_qs.exists():
                parent_obj = parent_qs.first()

        content = form.cleaned_data.get("content")
        new_comment, created = Comment.objects.get_or_create(
                            user= request.user,
                            content_type= content_type,
                            object_id = obj_id,
                            content= content,
                            parent= parent_obj,
                        )
        return HttpResponseRedirect(new_comment.parent.get_absolute_url())
        
    context = {
         'comment': obj,
         'form': form,
    }
    return render(request, "comments/comment_thread.html", context)

    #TODO: Edit comments

templates/comments/comment_thread.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}


<div class='col-sm-6 col-sm-offset-3 comment-thread'>
      <h1> Comment Thread </h1>
      <br />
      <p class='parent-comment'> {{comment.content}} </p>
      <footer class='parent-footer'> via {{ comment.user }} | {{comment.timestamp| timesince}} ago |
          {% if comment.children.count == 1 %} {{ comment.children.count }} Reply | {% endif %}
          {% if comment.children.count > 1 %} {{ comment.children.count }} Replies |{% endif %}
          {% if request.user == comment.user %} <a class='' href="{% url 'comments:delete' comment.id %}"> Delete  </a/>
            {% endif %}
        </footer>
        <hr />

      <!-- Replies -->
      <div>
        {% for child_comment in comment.children %}
          <blockquote>
            <p class='child-comment'> {{child_comment.content}} </p>
            <footer>
              via {{ child_comment.user }} | {{child_comment.timestamp| timesince}} ago
              {% if request.user == child_comment.user %}
                <a class='' href="{% url 'comments:delete' child_comment.id %}"> | Delete </a/>
              {% endif %}
            </footer>
          </blockquote>
          <hr />
        {% endfor %}
        {% if request.user.is_authenticated %}
          <form class='reply-form' method="POST" action="."> {% csrf_token %}
            {{ form | crispy }}
            <input type='hidden' name='parent_id' value='{{ comment.id }}' />
            <input type='submit' value='Reply' class='btn btn-default' />
          </form>
        {% else %}
          <br />
          <p > You must be logged in to reply.</p>
        {% endif %}
      </div>

</div>
{% endblock content %}

templates/comments/confirm_delete.html
{% extends "base.html" %}

{% block title %} Delete Comment {% endblock title %}

{% block content %}

<h1> Delete Comment </h1>

<div class='col-sm-6 col-sm-offset-3'>

    <form method="POST" action="."> {% csrf_token %}
      <p>
        Are you sure you wish to delete your comment: "{{object.content}}" ?
      </p>
      <input type='submit' value='Confirm' class='btn btn-warning'>
      <a href='{{object.get_absolute_url}}' class='btn btn-default'/> Cancel </a>
    </form>

</div>

{% endblock content %}